### ISSUE TITLE
Needs date and time for essays template

### ISSUE THREAD

**Issue by gczh** [smubia/smubia#2]
![image](https://user-images.githubusercontent.com/1908934/31165954-8571782a-a91f-11e7-8832-e4b1fbedccf6.png)

Currently we don't have any date time for the essays template (potentially the other templates that are for write-ups as well)

This is a problem as no one would know what when the write-up was written. This is also an issue for search-ability on sites like Google.

Pending Tasks for Issue:
- [x] Add Date and Time to Essays template

**Comment by lmhs** [comment]
Hi @gczh!
Please check this pull request: #12 
I have changed div to article tag and added time tag with special attributes to improve page semantics:

![screen shot 2017-10-08 at 15 38 31](https://user-images.githubusercontent.com/363187/31316881-fc804456-ac3e-11e7-8cb6-d3a1846e0fbd.png)
